main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About WCI"
    url: "/about-wci"
    weight: 2

  - name: "What We Do"
    url: "/what-we-do"
    weight: 3

  - name: "Chiba Prefecture"
    url: "/chiba-prefecture"
    weight: 4

  - name: "Donate"
    url: "/donate"
    weight: 5

buttons:
  - name: "Contact Us"
    url: "/contact"
    weight: 6

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About WCI"
    url: "/about-wci"
    weight: 2

  - name: "What We Do"
    url: "/what-we-do"
    weight: 3

  - name: "Chiba Prefecture"
    url: "/chiba-prefecture"
    weight: 4

  - name: "Donate"
    url: "/donate"
    weight: 6

  - name: "Contact Us"
    url: "/contact"
    weight: 7
